name: dapper
description: A simple Markdown and YAML formatter for Dart, inspired by Prettier.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  markdown: ^7.3.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
