name: dapper
description: A simple Markdown and YAML formatter for Dart, inspired by Prettier.
version: 0.1.0
repository: https://github.com/koji-1009/dapper
issue_tracker: https://github.com/koji-1009/dapper/issues

environment:
  sdk: ^3.8.0

dependencies:
  args: ^2.7.0
  markdown: ^7.3.0
  yaml: ^3.1.3

dev_dependencies:
  coverage: ^1.15.0
  lints: ^6.0.0
  test: ^1.25.6
